name: Protect main branch

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  check-main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check allowed source branches
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"

          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: $TARGET_BRANCH"

          if [[ "$TARGET_BRANCH" == "main" && "$SOURCE_BRANCH" == "staging-a" ]]; then
            echo "✅ PR autorisée depuis $SOURCE_BRANCH vers main"
            exit 0
          else
            echo "❌ PR refusée : seules la branche staging-a peut merger vers main"
            exit 1
          fi
